spring.application.name=spring-security-demo
server.port=8084


# Désactive le cache de Thymeleaf pendant le développement
spring.thymeleaf.cache=false

# Pour voir les logs de sécurité (utile pour déboguer)
logging.level.org.springframework.security=DEBUG